#!/bin/sh


cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: helloworld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: istio/examples-helloworld-v1
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: demo-senai
spec:
  gateways:
    - istio-autogenerated-k8s-ingress.istio-system.svc.cluster.local
  hosts:
    - agile-devops.club
  http:
    - match:
        - uri:
            prefix: /hello
      route:
        - destination:
            host: helloworld
            port:
              number: 5000

---
EOF

